#!/bin/bash
clear
# Change to the directory where this script is located
#cd $(dirname $(readlink -f $0))
cd "$(dirname "$BASH_SOURCE")" || exit

#enable extended regex
shopt -s extglob
PS3="MAIN MENU choose your option or press enter to show options again:  "
select task in createDB listDBs connectDB dropDB exit
do
  PS3="MAIN MENU choose your option or press enter to show options again:  "
  if [[ "$REPLY" = 5 || "$REPLY" = "exit" ]] ; then
    exit
  elif [[ "$REPLY" =~ ^[1-4]$ ]] ; then
      if [[ -f "./$task" && -x "./$task" ]]; then
        ./$task
      else
        echo "Script './$task' not found or not executable"
      fi
  else
    echo "Invalid option"
  fi
done


