#!/bin/bash
shopt -s extglob

PS3="enter number 1)createDB 2)listDBs 3)connectDB 4)dropDB 5)exit:  "
select task in createDB listDBs connectDB dropDB exit
do
  if [[ "$REPLY" = 5 || "$REPLY" = "exit" ]] ; then
  exit
  elif [[ "$REPLY" =~ ^[1-4]$ ]] ; then
      if [[ -f "./$task" && -x "./$task" ]]; then
        . "./$task"
      else
        echo "Script './$task' not found or not executable"
      fi

  else echo "Invalid option"
  fi
done


