#!/bin/bash

confirm_delete() {
    while true; do
        read -p "Are you sure you want to delete the database '$1'? (y/n): " choice
        case "$choice" in
            y|Y ) return 0;;
            n|N ) return 1;;
            * ) echo "Please answer y or n.";;
        esac
    done
}
dropDB(){
while true; do
    echo  "-----------------------------------------"
    if [ -z "$(ls ./DataBases 2> /dev/null)" ];then
      echo "there is no databases to drop"
      echo "-----------------------------------------"
      exit
    fi
    echo "Enter db name to drop or type 'exit' to return to the main menu"
    read -r DBname
    if [[ "$DBname" =~ ^[Bb][aA][cC][Kk]$ ]]; then
        echo "Back to main menu"
        echo "-----------------------------------------"
        return
    elif [[ "$DBname" =~ ^[eE][xX][iI][tT]$  ]] ; then
        echo "-----------------------------------------"
        return
    elif ! [[ "$DBname" =~ ^[a-zA-Z][A-Za-z_0-9]*$ ]]; then
        echo "Invalid DB Name"
    elif ! [ -d "./DataBases/$DBname" ]; then
        echo "Database '$DBname' doesn't exist"
    elif [ -d "./DataBases/$DBname" ]; then
        if confirm_delete "$DBname"; then
            rm -r "./DataBases/$DBname" && echo "DB '$DBname' deleted" || echo "Failed to delete DB '$DBname'"
        else
            echo "Deletion of DB '$DBname' canceled"
        fi
        echo "-----------------------------------------"
        break
    fi
done
}
dropDB