#!/bin/bash

listDBs() {
  if [ -d DataBases ]; then
    dbs=$(ls -F DataBases | grep '/' )
    if [ -z "$dbs" ]; then
      echo "No databases found."
    else
      echo "Databases in DataBases directory:"
      #loop to remove slash
      for i in $dbs
      do
        echo ${i%/}
        #echo ${i[@]:0:${#i}-1}
      done
    fi
  else
    echo "DataBases directory not found."
  fi
}

listDBs
