#!/bin/bash
shopt -s extglob
createDB (){
     while [ true ]
    do
     echo  "Enter Name of database to be created type back to return to main menu"
     read -r DBname
     if [[ $DBname =~ [Bb][aA][cC][Kk]  ]] ; then
      echo "back to main";break
     elif [ -d $DBname ] ; then echo "Database $DBname Already exists";break
     elif ! [[ $DBname =~  ^[a-zA-Z][A-Za-z_0-9]*$ ]] ; then
      echo "Invalid DB Name it must start with a letter and only contains letter numbers and underscores"
     else
      mkdir -p DataBases/$DBname
      echo "database $DBname created"
      break
      fi
    done
}

PS3="enter number 1)createDB 2)listDB 3)onnectDB 4)dropDB 5)exit "
select task in createDB listDB connectDB dropDB exit
do
  $task
done


